name: npm publish
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types: [assigned]
  
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: pnpm install
      - run: npm run test
